const BASE_URL = "/assets/images/courses/";
export const COURSES = [
  {
    title: "Advanced UI/UX Design Techniques",
    category: "UI-UX Design",
    slug: "ui-ux-design",
    description:
      "This course explores advanced techniques in UI/UX design to enhance user interfaces with innovative and interactive elements. Students will learn to integrate microinteractions, motion design, and sophisticated typography to create compelling digital experiences. The course also covers the strategic implementation of design systems and effective data visualization to support decision-making processes. Emphasis is placed on creating accessible and inclusive designs that adhere to global standards, ensuring a broad and engaging user experience.",
    what_you_will_learn: [
      "Design and implement microinteractions that enrich user interactions.",
      "Utilize motion design to guide, delight, and inform users effectively.",
      "Develop comprehensive design systems for maintaining consistency across platforms.",
      "Create impactful data visualizations and infographics for diverse audiences.",
      "Incorporate accessibility and inclusivity into everyday design practices, ensuring compliance with the latest standards.",
    ],
    duration: "16 weeks",
    lesson: "10",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "offline",
    certificate: "Yes",
    image: BASE_URL + "uiux.webp",
  },
  {
    title: "Application Development With Flutter",
    category: "App Development",
    slug: "app-development",
    description:
      "Our App Development Course is designed to equip learners with the skills required to build professional mobile applications from scratch. The program covers both Android and iOS development, focusing on modern frameworks, tools, and best practices. Participants will gain hands-on experience by developing real-world projects.",
    what_you_will_learn: [
      "Beginner-friendly to advanced levels.",
      "Learn Java, Kotlin, Swift, Dart, React Native, and Flutter.",
      "Practical training with live projects.",
      "Covers UI/UX design, APIs, Firebase, and backend integration.",
      "Guidance on App Store & Play Store publishing.",
    ],
    duration: "15 weeks",
    lesson: "10",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "flutter.webp",
  },
  {
    title: "Blockchain Development Fundamentals",
    category: "Blockchain Development",
    slug: "blockchain-development",
    description:
      "This course provides an in-depth introduction to the world of blockchain technology. Students will explore the foundational concepts of how blockchains operate, including the architecture of decentralized networks, consensus mechanisms like Proof of Work and Proof of Stake, and the security protocols that underpin blockchain reliability. The course offers hands-on experience with popular development tools such as Truffle and Ganache, and guides students through the process of developing, deploying, and interacting with smart contracts on Ethereum.",
    what_you_will_learn: [
      "Understand the core principles of blockchain technology and its transformative potential across industries.",
      "Gain proficiency in using key blockchain development tools and platforms.",
      "Develop and deploy smart contracts on Ethereum using Solidity.",
      "Create decentralized applications (DApps) that interact with blockchain technology.",
      "Evaluate and implement security best practices in blockchain development.",
    ],
    duration: "32 weeks",
    lesson: "15",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "blockchain.webp",
  },
  {
    title: "Modern Frontend Development with React",
    category: "Frontend Development",
    slug: "frontend-development",
    description:
      "This course offers an in-depth exploration of React, one of the most popular JavaScript libraries for building user interfaces. Students will learn about React's component-based architecture, state management, and lifecycle methods, along with modern hooks and advanced patterns for scalable application development.",
    what_you_will_learn: [
      "Master React's fundamentals, including JSX, components, and hooks.",
      "Implement state management in React applications using Context API and Redux.",
      "Utilize React Router for effective navigation and routing in web apps.",
      "Integrate APIs and external data sources into React applications.",
      "Adopt best practices for performance optimization and code organization.",
    ],
    duration: "24 weeks",
    lesson: "15",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "react.webp",
  },
  {
    title: "Full Stack Development with MERN",
    category: "Full Stack Development",
    slug: "full-stack-development",
    description:
      "This course provides a thorough introduction to full-stack development using the MERN stack (MongoDB, Express.js, React, Node.js). Students will build dynamic web applications from the ground up, learning both client-side and server-side development along with essential practices for integrating databases and APIs in a single cohesive project.",
    what_you_will_learn: [
      "Build and deploy full-stack web applications using the MERN stack.",
      "Understand backend development with Node.js and Express.js.",
      "Develop front-end interfaces with React and manage state with Redux.",
      "Integrate MongoDB for robust data storage solutions.",
      "Apply best practices for testing and deploying scalable applications.",
    ],
    duration: "35 weeks",
    lesson: "40",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "mern.webp",
  },
  {
    title: "Backend With Laravel Development",
    category: "Laravel Development",
    slug: "laravel-development",
    description:
      "Our Laravel Development Course is designed to help learners master one of the most popular and powerful PHP frameworks. Laravel is widely used for building secure, scalable, and high-performance web applications. This course covers everything from Laravel fundamentals to advanced concepts such as authentication, APIs, and deployment, enabling participants to become job-ready full-stack developers.",
    what_you_will_learn: [
      "Beginner to advanced level training.",
      "Covers MVC architecture & Laravel best practices.",
      "Hands-on experience with Eloquent ORM, Blade, Artisan & Middleware.",
      "Real-world projects: CMS, E-commerce, and APIs.",
      "Integration with MySQL, RESTful APIs, and third-party services.",
      "Deployment on cPanel & cloud servers.",
    ],
    duration: "12 weeks",
    lesson: "10",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "laravel.webp",
  },
  {
    title: "Building Scalable Applications with Next.js",
    category: "Next.js Development",
    slug: "nextjs-development",
    description:
      "This course provides a thorough introduction to building scalable web applications using Next.js, the React framework for production. Students will create high-performance applications from the ground up, learning both client-side and server-side development with Next.js's integrated features, along with essential practices for database integration and API development in a single cohesive framework.",
    what_you_will_learn: [
      "Build and deploy scalable web applications using Next.js and React.",
      "Understand server-side rendering (SSR) and static site generation (SSG) with Next.js.",
      "Develop dynamic front-end interfaces with React and manage state effectively.",
      "Create API routes and integrate databases like MongoDB for robust data storage.",
      "Apply best practices for performance optimization, testing, and deploying scalable Next.js applications.",
    ],
    duration: "35 weeks",
    lesson: "40",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "nextjs.webp",
  },
  {
    title: "Node.js Backend Development",
    category: "Node.js Backend Development",
    slug: "nodejs-backend-development",
    description:
      "This course focuses on backend development using Node.js, exploring its non-blocking architecture and event-driven environment. Students will learn to build scalable and efficient web services and APIs using Express.js, and integrate databases like MongoDB and SQL. Security, performance optimization, and real-time data processing are also covered extensively.",
    what_you_will_learn: [
      "Develop high-performance server-side applications with Node.js.",
      "Create RESTful APIs using Express.js.",
      "Integrate various database technologies for persistent data storage.",
      "Implement security measures and performance optimizations.",
      "Utilize modern tools and techniques for efficient backend development.",
    ],
    duration: "24 weeks",
    lesson: "18",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "nodejs.webp",
  },
  {
    title: "Backend With PHP Development",
    category: "PHP Development",
    slug: "php-development",
    description:
      "Our PHP Development Course is designed to train learners in building powerful, scalable, and dynamic web applications using PHP. The program covers Core PHP, advanced concepts, and popular frameworks such as Laravel & CodeIgniter, along with front-end technologies for full-stack development. By the end of the course, participants will be able to design, develop, and deploy professional-grade web applications.",
    what_you_will_learn: [
      "Beginner-friendly and industry-focused curriculum.",
      "Covers Core PHP, OOP, and MVC architecture.",
      "Hands-on training in MySQL database integration.",
      "Practical projects: blogs, e-commerce, and custom apps.",
      "Training on Laravel, CodeIgniter, and RESTful APIs.",
      "Deployment on hosting servers & version control (Git).",
    ],
    duration: "16 weeks",
    lesson: "12",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "php.webp",
  },
  {
    title: "Backend With Python Development",
    category: "Python Development",
    slug: "python-development",
    description:
      "Our Python Development Course is designed to provide learners with in-demand programming skills and hands-on experience in Python, one of the most popular and versatile programming languages in the world. The course covers everything from the basics to advanced development concepts, including web development, data handling, automation, and frameworks.",
    what_you_will_learn: [
      "Beginner-friendly with step-by-step progression.",
      "Practical coding sessions and live projects.",
      "Covers Core Python, OOP, File Handling, and Libraries.",
      "Introduction to Flask & Django (Web Development).",
      "Data handling with Pandas & NumPy.",
      "Real-world projects: automation scripts, web apps, APIs.",
    ],
    duration: "15 weeks",
    lesson: "10",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "python.webp",
  },
  {
    title: "Responsive Web Design Essentials",
    category: "Responsive Web Design",
    slug: "responsive-web-design",
    description:
      "This course teaches the fundamentals of responsive web design, focusing on flexible layouts, responsive images, and CSS media queries. Students will learn how to build websites that look great and function properly on any device, from desktops to smartphones, ensuring a seamless user experience.",
    what_you_will_learn: [
      "Understand the core principles of responsive design.",
      "Create flexible layouts using CSS Grid and Flexbox.",
      "Implement media queries to adapt website design to different devices.",
      "Optimize images and multimedia for faster loading and better performance.",
      "Ensure accessibility and usability in responsive designs.",
    ],
    duration: "16 weeks",
    lesson: "6",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "responsive.webp",
  },
  {
    title: "Master the Art of Web Design",
    category: "Web Design",
    slug: "web-design",
    description:
      "This comprehensive course delves into the artistic and technical aspects of web design. It covers essential design principles, advanced user interface techniques, and the psychology of colors and typography. Students will learn to craft aesthetically pleasing and functional designs, understand user behavior, and apply responsive design principles to ensure accessibility and usability across various devices.",
    what_you_will_learn: [
      "Master fundamental and advanced design principles.",
      "Apply color theory and typography effectively to enhance user experience.",
      "Create responsive and accessible web designs that perform well across devices.",
      "Utilize tools like Adobe XD, Figma, and Sketch for high-fidelity prototyping.",
      "Develop a comprehensive understanding of user psychology and behavior in web design.",
    ],
    duration: "16 weeks",
    lesson: "10",
    timing: "10:00 - 07:00",
    language: "English",
    qualifications: "Graduate",
    mode: "Offline",
    certificate: "Yes",
    image: BASE_URL + "html-css-js.webp",
  },
];
