export const ICON_ASSETS = {
    HOME: "mdi:home",
    EMPLOYEES: "mdi:account-group",
    USER: "mdi:account",
    LOGOUT: "mdi:logout",
    CALENDAR: "mdi:calendar",
    WEBSITE: "mdi:web",
    PORTFOLIO: "mdi:briefcase",
    SERVICES: "mdi:cog",
    COURSES: "mdi:school",
    BLOGS: "mdi:post",
    SEARCH: "mdi:magnify",
    EYE:"mdi:eye",
    LIVE:"",
    BROKEN_IMAGE:"mdi:image-broken",
    DELETE:"mdi:delete",
    DRAG:"mdi:drag",
    ADD:"mdi:plus",
    CATEGORY:"carbon:category",
};
