const BASE_URL = "/assets/images/";
const LOGO_BASE = BASE_URL + "logo/";
const SERVICE_BASE = BASE_URL + "services/";
const TEAM_BASE = BASE_URL + "team/";

export const IMAGE_ASSETS = {
  LOGO: LOGO_BASE + "logo-light.webp",
  LOGO_SYMBOL: LOGO_BASE + "logo-light-symbol.webp",
  SCROLL_TOP: LOGO_BASE + "scroll_top.svg",
  NOT_FOUND: BASE_URL + "404.gif",
  HERO_SECTION_1: BASE_URL + "earth.webp",
  HERO_SECTION_2: BASE_URL + "code.webp",

  SERVICE_IMG: {
    BLOCKCHAIN: SERVICE_BASE + "blockchain-dev.webp",
    CMS_DEV: SERVICE_BASE + "cms-dev.webp",
    CUSTOM_DEV: SERVICE_BASE + "custom-dev.webp",
    ECOMMERCE_DEV: SERVICE_BASE + "ecommerce-dev.webp",
    GRAPHIC_DESIGN: SERVICE_BASE + "graphic-des.webp",
    INVENTORY_DEV: SERVICE_BASE + "inventory-dev.webp",
    JS_DEV: SERVICE_BASE + "js-dev.webp",
    GOOGLE_ADS: SERVICE_BASE + "google-ads.webp",
    META_ADS: SERVICE_BASE + "meta-ads.webp",
    MOBILE_APP_DEV: SERVICE_BASE + "mobile-app-dev.webp",
    UIUX_DESIGN: SERVICE_BASE + "ui-ux.webp",
    WORDPRESS_DEV: SERVICE_BASE + "wordpress-dev.webp",
  },

  TOOLS: [
    "logos:vue",
    "devicon:nextjs",
    "catppuccin:javascript-react",
    "vscode-icons:file-type-angular",
    "devicon:nuxtjs",
    "logos:nodejs-icon-alt",
    "simple-icons:express",
    "devicon:laravel",
    "devicon:dotnetcore",
    "logos:javascript",
    "logos:typescript-icon",
    "devicon:python",
    "devicon:java",
    "devicon:go",
    "simple-icons:rust",
    "devicon:kotlin",
    "devicon:swift",
    "devicon:dart",
    "logos:ruby",
    "vscode-icons:file-type-flutter",
    "devicon:mysql",
    "devicon:postgresql",
    "devicon:mongodb",
    "devicon:redis",
    "mdi:aws",
    "devicon:azure",
    "devicon:googlecloud",
    "vscode-icons:file-type-html",
    "vscode-icons:file-type-css",
    "logos:sass",
    "logos:tailwindcss-icon",
    "devicon:bootstrap",
    "logos:material-ui",
    "devicon:jquery",
    "logos:redux",
    "logos:shopify",
    "devicon:figma",
    "devicon:git",
    "logos:postman-icon",
    "vscode-icons:file-type-solidity",
  ],
  
   TEAM : [
    TEAM_BASE + "abhay.webp", //1
    TEAM_BASE + "chintanbhai.webp",
    TEAM_BASE + "devan.webp",
    TEAM_BASE + "dixit.webp",
    TEAM_BASE + "ghanshyam.webp",
    TEAM_BASE + "jiya.webp",
    TEAM_BASE + "kashyap.webp",
    TEAM_BASE + "krina.webp",
    TEAM_BASE + "krupali.webp",
    TEAM_BASE + "miten.webp", //10
    TEAM_BASE + "nemisha.webp",
    TEAM_BASE + "payal.webp",
    TEAM_BASE + "ravibhai.webp",
    TEAM_BASE + "rohan.webp",
    TEAM_BASE + "shivang.webp",
    TEAM_BASE + "taman.webp",
    TEAM_BASE + "trushit.webp",
    TEAM_BASE + "utsav.webp",
    TEAM_BASE + "vansh.webp",
    TEAM_BASE + "vishva.webp", //20
    TEAM_BASE + "princy.webp",
    TEAM_BASE + "aaryan.webp",
    TEAM_BASE + "viren.webp",
    TEAM_BASE + "chintanbhai.webp",
  ]
  
};
